-- 코드를 입력하세요
SELECT CAR_ID, a.CAR_TYPE, FLOOR(DAILY_FEE*30*(1-DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)

WHERE a.CAR_TYPE IN ('SUV','세단') 
    AND CAR_ID NOT IN(SELECT CAR_ID
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                     WHERE END_DATE >= '2022-11-1'
                        AND START_DATE <= '2022-11-30')
    AND DURATION_TYPE = '30일 이상'
HAVING FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;