-- 코드를 입력하세요
SELECT ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a
    JOIN ANIMAL_OUTS b USING (ANIMAL_ID)
WHERE a.SEX_UPON_INTAKE LIKE 'Intact%' AND (b.SEX_UPON_OUTCOME LIKE 'Spayed%' or b.SEX_UPON_OUTCOME LIKE  'Neutered%')
GROUP BY ANIMAL_ID
ORDER BY ANIMAL_ID