-- 코드를 입력하세요
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(a.PRICE * b.AMOUNT)AS TOTAL_SALES
FROM FOOD_PRODUCT a
    JOIN FOOD_ORDER b USING (PRODUCT_ID)
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) ='05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;