-- 코드를 입력하세요
SELECT HISTORY_ID, 
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE)+1 < 7 THEN DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1)
        WHEN DATEDIFF(END_DATE, START_DATE)+1 < 30 THEN FLOOR (DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE DURATION_TYPE = '7일 이상'AND CAR_TYPE ='트럭')/100))
        WHEN DATEDIFF(END_DATE, START_DATE)+1 < 90 THEN FLOOR (DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
        WHERE DURATION_TYPE = '30일 이상'AND CAR_TYPE ='트럭')/100))
        ELSE FLOOR (DAILY_FEE * (DATEDIFF(END_DATE, START_DATE)+1) * (1-(SELECT DISCOUNT_RATE
                                                                     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                                                                     WHERE DURATION_TYPE = '90일 이상' 
                                                                             AND CAR_TYPE ='트럭')/100))
    END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    JOIN CAR_RENTAL_COMPANY_CAR  USING (CAR_ID)
WHERE CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
HAVING FEE > 0
ORDER BY FEE DESC, HISTORY_ID DESC;